name       : haskell-pretty-show
version    : '1.7'
release    : 2
source     :
    - http://hackage.haskell.org/package/pretty-show-1.7/pretty-show-1.7.tar.gz : 382b6ef4a78e4059611b5c86674ad72a6bfce821e8852da4f00b628cfbbc272f
license    : MIT
component  : programming.haskell
summary    : We provide a library and an executable for working with derived Show instances.
description: |
    We provide a library and an executable for working with derived Show instances.
builddeps  :
    - haskell-cabal-install
    - haskell-happy
    - haskell-lexer
    - haskell-pretty
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
