name       : haskell-pretty-show
version    : '1.10'
release    : 3
source     :
    - https://hackage.haskell.org/package/pretty-show-1.10/pretty-show-1.10.tar.gz : 307f9086e0b063d439dc4f513e36a145e8a57f23de448aefae2a6c00f6da6fd2
license    : MIT
component  : programming.haskell
summary    : We provide a library and an executable for working with derived Show instances.
description: |
    We provide a library and an executable for working with derived Show instances.
builddeps  :
    - haskell-cabal-install
    - haskell-fail-devel
    - haskell-happy
    - haskell-lexer-devel
rundeps    :
    - devel:
        - haskell-fail-devel
        - haskell-happy
        - haskell-lexer-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
