name       : haskell-pretty-show
version    : 1.6.12
release    : 1
source     :
    - https://hackage.haskell.org/package/pretty-show-1.6.12/pretty-show-1.6.12.tar.gz : 9629c98ac0f2eb215cd81cf61321c5181acd18df35d89817093e934f786774b9
license    : MIT
component  : programming.haskell
summary    : We provide a library and an executable for working with derived Show instances.
description: |
    We provide a library and an executable for working with derived Show instances.
builddeps  :
    - haskell-cabal-install
    - haskell-happy
    - haskell-lexer
    - haskell-pretty
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
